### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by banerjeeshubhanker** [TeangaNLP/teanga2#2] opened 2024-02-12 12:58 UTC
When installing the wheel file with Python 3.10 using pip on Ubuntu 20.04 and OpenSUSE Leap15.5 an error message shows up:
ERROR: teanga-0.1.0-cp310-cp310-manylinux_2_34_x86_64.whl is not a supported wheel on this platform.

**Comment by jmccrae** [comment] 2024-02-15 09:24
I think the version on that machine is Python 3.11

The problem is that I need to compile more versions of the wheel.

This version should work https://github.com/TeangaNLP/teanga2/releases/download/dev-latest-linux/teanga-0.1.0-cp311-cp311-manylinux_2_34_x86_64.whl

**Comment by jmccrae** [comment] 2024-03-27 12:23
Fixed now. The Rust code is its own project, so this repo can be installed in pure Python

**Closed** 2024-03-27 12:24 UTC
